# Generated by Django 4.0.5 on 2022-06-10 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('short_url', models.CharField(max_length=10, unique=True)),
                ('long_url', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
